
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: always

  nginx:
    build:
      context: ./infra/nginx
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - frontend
    restart: always

networks:
  app-network:
    driver: bridge
